server :
  port : 5025
  forward-headers-strategy: framework

spring:
  rabbitmq:
    addresses: localhost
    port: 5672

  cloud:
    stream:
      bindings:
        publishConfigUpdate-out-0:
          destination: config.update
      source: publishConfigUpdate
