server :
  port : 5025

spring:
  rabbitmq:
    addresses: localhost
    port: 5672

  cloud:
    function:
      definition: publishConfigUpdate
    stream:
      bindings:
        publishConfigUpdate-out-0:
          destination: config.update