server :
  forward-headers-strategy: framework

spring:
  profiles:
    active: default,local

  rabbitmq:
    addresses: rabbitmq
    port: 5672

  cloud:
    stream:
      bindings:
        publishConfigUpdate-out-0:
          destination: config.update
      source: publishConfigUpdate
